project_id = "xmiozlzflqpcgmghckem"

[functions.parse-equipment-docs]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset-confirmation]
verify_jwt = false

[functions.admin-test-email]
verify_jwt = false
